### ISSUE TITLE
如何指定运行的端口？

### ISSUE THREAD

**Issue by luckypoem** [RicterZ/pyprint#7]
我的8080端口已被占用。
谢谢

**Comment by RicterZ** [comment]
ˊ_>ˋ我后台还没写完......军训完（7.12）才回去填坑orz
可以 python main.py 8888 这样运行..但是推荐uwsgi

发自我的 iPad

**Comment by luckypoem** [comment]
hi.
初步搭建好：http://as3.brite.biz:3426/ ，登录地址是什么？
哦，你说“后台还没写完”，不过不明白你如何登录你的网站http://www.ricter.me/ ？

**Comment by RicterZ** [comment]
/signin

后台还不能发表文章..就有个添加友链..

发自我的 iPad

**Comment by JmPotato** [comment]
噗，要他何用
